# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nightly Builds for Legacy

on:
  push:
    branches: 
      - "legacy/**"
    paths:
      - "src/**/*.java"
      - "pom.xml"
      - ".github/workflows/*"
  pull_request:
    branches:
      - "legacy/**"
    paths:
      - "src/**/*.java"
      - "pom.xml"
      - ".github/workflows/*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mc-version: [1.8.8, 1.12.2]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Spigot Build Environment for ${{ matrix.mc-version }}
        run: |
          mkdir BuildTools
          cd BuildTools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev ${{ matrix.mc-version }}
          cd ..
      - name: Change target version to ${{ matrix.mc-version }}
        run: |
          ./.github/workflow-files/change-ver.sh ${{ matrix.mc-version }}
      - name: Build with Maven
        run: mvn package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Client-${{ matrix.mc-version }}.jar
          # A file, directory or wildcard pattern that describes what to upload
          path: target/**/*.jar
