# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release for Legacy Systems

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mc-version: [1.8.8, 1.12.2]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Spigot Build Environment for ${{ matrix.mc-version }}
        run: |
          mkdir BuildTools
          cd BuildTools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev ${{ matrix.mc-version }}
          cd ..
      - name: Change target version to ${{ matrix.mc-version }}
        run: |
          ./.github/workflow-files/change-ver.sh ${{ matrix.mc-version }}
      - name: Update version of maven file to ${{ github.event.release.tag_name }}
        run: mvn versions:set -DnewVersion=${VER_TAG:1}
        env:
          VER_TAG: ${{ github.event.release.tag_name }}
      - name: Build with Maven
        run: mvn package
      - name: Rename pacakge
        run: |
          mkdir releases
          mv target/client-${VER_TAG:1}.jar releases/client-${VER_TAG:1}-mc${MC_VERSION}.jar
        env:
          VER_TAG: ${{ github.event.release.tag_name }}
          MC_VERSION: ${{ matrix.mc-version }}
      - name: Upload packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/client-*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Commit updated version info to github
        run: |
          git add pom.xml
          git config user.name Alex4386
          git config user.email psh010209@gmail.com
          git commit -m "chore: bump up version to ${VER_TAG:1}"
          git push
